cc_binary(
    name = "iotest",
    srcs = ["iotest.cpp"],
)

cc_binary(
    name = "whiletest",
    srcs = ["whiletest.cpp"]
)

cc_binary(
    name = "readmultinum",
    srcs = ["readmultinum.cpp"]
)

