cc_binary(
    name = "sales_item_app",
    srcs = ["Sales_item.cpp"],
    deps = [
        "sales_item_lib",
    ],
)

cc_library(
    name = "sales_item_lib",
    hdrs = ["Sales_item.h"],
    visibility = ["//visibility:public"],
)
